# Generated by Django 5.1.2 on 2024-10-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_function', '0002_alter_sitesformat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesformat',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitesformat',
            name='htmlcontent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sitesformat',
            name='jsoncontent',
            field=models.TextField(null=True),
        ),
    ]
