# Generated by Django 5.1.2 on 2024-10-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_function', '0003_alter_sitesformat_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesformat',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesformat',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
